#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package EDAMTypes::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant CLASSIFICATION_RECIPE_USER_NON_RECIPE => "000";

use constant CLASSIFICATION_RECIPE_USER_RECIPE => "001";

use constant CLASSIFICATION_RECIPE_SERVICE_RECIPE => "002";

use constant EDAM_NOTE_SOURCE_WEB_CLIP => "web.clip";

use constant EDAM_NOTE_SOURCE_MAIL_CLIP => "mail.clip";

use constant EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY => "mail.smtp";

1;
